model_path: /data/horse/ws/dchristi-3dseg/checkpoints/DFG_Benni/model_2025-11-29_02/last_checkpoint.pytorch
device: cuda:0
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 3
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 48
  # number of groups in the groupnorm
  num_groups: 8
  # number of levels in the encoder/decoder path (applied only if f_maps is an int)
  num_levels: 4
  # down-pooling type for encoder branch: ["max", "avg", "conv"] 
  pool_type: conv
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: false
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  is_segmentation: true
predictor:
  name: 'StandardPredictor'
  output_type: 'probability' # 'probability' otherwise "class": performs torch.argmax [c,spatial] to [spatial] with c as int label
  precision: float16
loaders:
  dataset: StandardHDF5Dataset
  # save predictions to output_dir
  output_dir: /data/horse/ws/dchristi-3dseg/last_checkpoint #results/ # # #
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 8
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  mirror_padding: [16, 16, 16]
  # how many subprocesses to use for data loading
  num_workers: 24
  # path to the raw data within the H5
  raw_internal_path: /volume
  # test loaders configuration
  test:
    file_paths:
      - /data/horse/ws/dchristi-3dseg/data/DFG_Benni/Probe4_klein/Probe4_klein.h5
    slice_builder:
      name: FilterSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem,
      # generally the bigger patch the better) origninal [128,128,128]
      patch_shape: [20, 128, 128]
      # train stride between patches
      stride_shape: [10, 96, 96]
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
